#!/bin/bash

echo "========================================"
echo "  ClientFlow - Current Credentials"
echo "========================================"
echo ""
echo "✅ WORKING CREDENTIALS (Required):"
echo "------------------------------------"
echo "DATABASE_URL=postgresql://estebanchirinos@localhost:5432/clientflow"
echo "APP_ORIGIN=http://localhost:3000"
echo "OWNER_SESSION_SECRET=UaThN7okw22ddynJgVQBqtkH1etOl32+hwnTz1pzosk="
echo "CLIENT_JWT_SECRET=XjWGzX2MVOLVhZGGeS+ZARTDfb+qWt0sNOPLLpRNncw="
echo "BYPASS_AUTH=true"
echo ""
echo "🔐 LOGIN CREDENTIALS:"
echo "------------------------------------"
echo "Email: owner@acme.com"
echo "Password: password123"
echo ""
echo "Or:"
echo "Email: admin@test.com"
echo "Password: admin123"
echo ""
echo "❌ MISSING CREDENTIALS (Optional):"
echo "------------------------------------"
echo ""
echo "📦 AWS S3 (for file uploads):"
echo "  1. Go to: https://console.aws.amazon.com"
echo "  2. Create S3 bucket"
echo "  3. Create IAM user with S3 access"
echo "  4. Add to .env.local:"
echo "     S3_REGION=us-east-1"
echo "     S3_BUCKET=your-bucket-name"
echo "     S3_ACCESS_KEY_ID=AKIA..."
echo "     S3_SECRET_ACCESS_KEY=..."
echo ""
echo "💳 Stripe (for payments):"
echo "  1. Go to: https://dashboard.stripe.com/register"
echo "  2. Get test API key"
echo "  3. Add to .env.local:"
echo "     STRIPE_SECRET_KEY=sk_test_..."
echo ""
echo "📊 HubSpot (for CRM):"
echo "  1. Go to: https://app.hubspot.com/signup"
echo "  2. Settings → Integrations → Private Apps"
echo "  3. Create app with scopes: crm.objects.contacts, crm.objects.deals"
echo "  4. Add to .env.local:"
echo "     HUBSPOT_PRIVATE_APP_TOKEN=pat-na1-..."
echo "     HUBSPOT_BASE_URL=https://api.hubapi.com"
echo ""
echo "========================================"
echo "  🚀 READY TO START!"
echo "========================================"
echo ""
echo "Run: npm run dev"
echo "Then go to: http://localhost:3000/login"
echo ""
